//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Model", "fk_Corredor_has_Corrida_Corredor", "corredor", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WcfRestService1.corredor), "inscricao", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WcfRestService1.inscricao))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Model", "fk_Corredor_has_Corrida_Corrida1", "corrida", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WcfRestService1.corrida), "inscricao", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WcfRestService1.inscricao))]

// Original file name:
// Generation date: 27/06/2015 14:18:48
namespace WcfRestService1
{
    
    /// <summary>
    /// There are no comments for webserviceEntities in the schema.
    /// </summary>
    public partial class webserviceEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new webserviceEntities object using the connection string found in the 'webserviceEntities' section of the application configuration file.
        /// </summary>
        public webserviceEntities() : 
                base("name=webserviceEntities", "webserviceEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new webserviceEntities object.
        /// </summary>
        public webserviceEntities(string connectionString) : 
                base(connectionString, "webserviceEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new webserviceEntities object.
        /// </summary>
        public webserviceEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "webserviceEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for corredor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<corredor> corredor
        {
            get
            {
                if ((this._corredor == null))
                {
                    this._corredor = base.CreateQuery<corredor>("[corredor]");
                }
                return this._corredor;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<corredor> _corredor;
        /// <summary>
        /// There are no comments for corrida in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<corrida> corrida
        {
            get
            {
                if ((this._corrida == null))
                {
                    this._corrida = base.CreateQuery<corrida>("[corrida]");
                }
                return this._corrida;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<corrida> _corrida;
        /// <summary>
        /// There are no comments for inscricao in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<inscricao> inscricao
        {
            get
            {
                if ((this._inscricao == null))
                {
                    this._inscricao = base.CreateQuery<inscricao>("[inscricao]");
                }
                return this._inscricao;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<inscricao> _inscricao;
        /// <summary>
        /// There are no comments for corredor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTocorredor(corredor corredor)
        {
            base.AddObject("corredor", corredor);
        }
        /// <summary>
        /// There are no comments for corrida in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTocorrida(corrida corrida)
        {
            base.AddObject("corrida", corrida);
        }
        /// <summary>
        /// There are no comments for inscricao in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToinscricao(inscricao inscricao)
        {
            base.AddObject("inscricao", inscricao);
        }
    }
    /// <summary>
    /// There are no comments for Model.corredor in the schema.
    /// </summary>
    /// <KeyProperties>
    /// idCorredor
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="corredor")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class corredor : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new corredor object.
        /// </summary>
        /// <param name="idCorredor">Initial value of idCorredor.</param>
        /// <param name="nome">Initial value of nome.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static corredor Createcorredor(int idCorredor, string nome)
        {
            corredor corredor = new corredor();
            corredor.idCorredor = idCorredor;
            corredor.nome = nome;
            return corredor;
        }
        /// <summary>
        /// There are no comments for property idCorredor in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int idCorredor
        {
            get
            {
                return this._idCorredor;
            }
            set
            {
                this.OnidCorredorChanging(value);
                this.ReportPropertyChanging("idCorredor");
                this._idCorredor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idCorredor");
                this.OnidCorredorChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _idCorredor;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidCorredorChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidCorredorChanged();
        /// <summary>
        /// There are no comments for property nome in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string nome
        {
            get
            {
                return this._nome;
            }
            set
            {
                this.OnnomeChanging(value);
                this.ReportPropertyChanging("nome");
                this._nome = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("nome");
                this.OnnomeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _nome;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnomeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnomeChanged();
        /// <summary>
        /// There are no comments for property data_nascimento in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> data_nascimento
        {
            get
            {
                return this._data_nascimento;
            }
            set
            {
                this.Ondata_nascimentoChanging(value);
                this.ReportPropertyChanging("data_nascimento");
                this._data_nascimento = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("data_nascimento");
                this.Ondata_nascimentoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _data_nascimento;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondata_nascimentoChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondata_nascimentoChanged();
        /// <summary>
        /// There are no comments for property cidade in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string cidade
        {
            get
            {
                return this._cidade;
            }
            set
            {
                this.OncidadeChanging(value);
                this.ReportPropertyChanging("cidade");
                this._cidade = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("cidade");
                this.OncidadeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _cidade;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncidadeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncidadeChanged();
        /// <summary>
        /// There are no comments for property estado in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string estado
        {
            get
            {
                return this._estado;
            }
            set
            {
                this.OnestadoChanging(value);
                this.ReportPropertyChanging("estado");
                this._estado = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("estado");
                this.OnestadoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _estado;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnestadoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnestadoChanged();
        /// <summary>
        /// There are no comments for property status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string status
        {
            get
            {
                return this._status;
            }
            set
            {
                this.OnstatusChanging(value);
                this.ReportPropertyChanging("status");
                this._status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("status");
                this.OnstatusChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _status;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnstatusChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnstatusChanged();
        /// <summary>
        /// There are no comments for inscricao in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "fk_Corredor_has_Corrida_Corredor", "inscricao")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<inscricao> inscricao
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<inscricao>("Model.fk_Corredor_has_Corrida_Corredor", "inscricao");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<inscricao>("Model.fk_Corredor_has_Corrida_Corredor", "inscricao", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Model.corrida in the schema.
    /// </summary>
    /// <KeyProperties>
    /// idCorrida
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="corrida")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class corrida : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new corrida object.
        /// </summary>
        /// <param name="idCorrida">Initial value of idCorrida.</param>
        /// <param name="nome">Initial value of nome.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static corrida Createcorrida(int idCorrida, string nome)
        {
            corrida corrida = new corrida();
            corrida.idCorrida = idCorrida;
            corrida.nome = nome;
            return corrida;
        }
        /// <summary>
        /// There are no comments for property idCorrida in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int idCorrida
        {
            get
            {
                return this._idCorrida;
            }
            set
            {
                this.OnidCorridaChanging(value);
                this.ReportPropertyChanging("idCorrida");
                this._idCorrida = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idCorrida");
                this.OnidCorridaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _idCorrida;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidCorridaChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidCorridaChanged();
        /// <summary>
        /// There are no comments for property nome in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string nome
        {
            get
            {
                return this._nome;
            }
            set
            {
                this.OnnomeChanging(value);
                this.ReportPropertyChanging("nome");
                this._nome = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("nome");
                this.OnnomeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _nome;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnomeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnomeChanged();
        /// <summary>
        /// There are no comments for property descricao in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string descricao
        {
            get
            {
                return this._descricao;
            }
            set
            {
                this.OndescricaoChanging(value);
                this.ReportPropertyChanging("descricao");
                this._descricao = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("descricao");
                this.OndescricaoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _descricao;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndescricaoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndescricaoChanged();
        /// <summary>
        /// There are no comments for property data_corrida in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> data_corrida
        {
            get
            {
                return this._data_corrida;
            }
            set
            {
                this.Ondata_corridaChanging(value);
                this.ReportPropertyChanging("data_corrida");
                this._data_corrida = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("data_corrida");
                this.Ondata_corridaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _data_corrida;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondata_corridaChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondata_corridaChanged();
        /// <summary>
        /// There are no comments for property cidade in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string cidade
        {
            get
            {
                return this._cidade;
            }
            set
            {
                this.OncidadeChanging(value);
                this.ReportPropertyChanging("cidade");
                this._cidade = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("cidade");
                this.OncidadeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _cidade;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncidadeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncidadeChanged();
        /// <summary>
        /// There are no comments for property estado in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string estado
        {
            get
            {
                return this._estado;
            }
            set
            {
                this.OnestadoChanging(value);
                this.ReportPropertyChanging("estado");
                this._estado = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("estado");
                this.OnestadoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _estado;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnestadoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnestadoChanged();
        /// <summary>
        /// There are no comments for property valor in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<double> valor
        {
            get
            {
                return this._valor;
            }
            set
            {
                this.OnvalorChanging(value);
                this.ReportPropertyChanging("valor");
                this._valor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("valor");
                this.OnvalorChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<double> _valor;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvalorChanging(global::System.Nullable<double> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvalorChanged();
        /// <summary>
        /// There are no comments for property status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string status
        {
            get
            {
                return this._status;
            }
            set
            {
                this.OnstatusChanging(value);
                this.ReportPropertyChanging("status");
                this._status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("status");
                this.OnstatusChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _status;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnstatusChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnstatusChanged();
        /// <summary>
        /// There are no comments for inscricao in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "fk_Corredor_has_Corrida_Corrida1", "inscricao")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<inscricao> inscricao
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<inscricao>("Model.fk_Corredor_has_Corrida_Corrida1", "inscricao");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<inscricao>("Model.fk_Corredor_has_Corrida_Corrida1", "inscricao", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Model.inscricao in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Corredor_idCorredor
    /// Corrida_idCorrida
    /// idInscricao
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="inscricao")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class inscricao : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new inscricao object.
        /// </summary>
        /// <param name="corredor_idCorredor">Initial value of Corredor_idCorredor.</param>
        /// <param name="corrida_idCorrida">Initial value of Corrida_idCorrida.</param>
        /// <param name="idInscricao">Initial value of idInscricao.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static inscricao Createinscricao(int corredor_idCorredor, int corrida_idCorrida, int idInscricao)
        {
            inscricao inscricao = new inscricao();
            inscricao.Corredor_idCorredor = corredor_idCorredor;
            inscricao.Corrida_idCorrida = corrida_idCorrida;
            inscricao.idInscricao = idInscricao;
            return inscricao;
        }
        /// <summary>
        /// There are no comments for property Corredor_idCorredor in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Corredor_idCorredor
        {
            get
            {
                return this._Corredor_idCorredor;
            }
            set
            {
                this.OnCorredor_idCorredorChanging(value);
                this.ReportPropertyChanging("Corredor_idCorredor");
                this._Corredor_idCorredor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Corredor_idCorredor");
                this.OnCorredor_idCorredorChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Corredor_idCorredor;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCorredor_idCorredorChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCorredor_idCorredorChanged();
        /// <summary>
        /// There are no comments for property Corrida_idCorrida in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Corrida_idCorrida
        {
            get
            {
                return this._Corrida_idCorrida;
            }
            set
            {
                this.OnCorrida_idCorridaChanging(value);
                this.ReportPropertyChanging("Corrida_idCorrida");
                this._Corrida_idCorrida = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Corrida_idCorrida");
                this.OnCorrida_idCorridaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Corrida_idCorrida;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCorrida_idCorridaChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCorrida_idCorridaChanged();
        /// <summary>
        /// There are no comments for property idInscricao in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int idInscricao
        {
            get
            {
                return this._idInscricao;
            }
            set
            {
                this.OnidInscricaoChanging(value);
                this.ReportPropertyChanging("idInscricao");
                this._idInscricao = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idInscricao");
                this.OnidInscricaoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _idInscricao;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidInscricaoChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidInscricaoChanged();
        /// <summary>
        /// There are no comments for property status_pagamento in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string status_pagamento
        {
            get
            {
                return this._status_pagamento;
            }
            set
            {
                this.Onstatus_pagamentoChanging(value);
                this.ReportPropertyChanging("status_pagamento");
                this._status_pagamento = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("status_pagamento");
                this.Onstatus_pagamentoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _status_pagamento;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onstatus_pagamentoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onstatus_pagamentoChanged();
        /// <summary>
        /// There are no comments for corredor in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "fk_Corredor_has_Corrida_Corredor", "corredor")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public corredor corredor
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<corredor>("Model.fk_Corredor_has_Corrida_Corredor", "corredor").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<corredor>("Model.fk_Corredor_has_Corrida_Corredor", "corredor").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for corredor in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<corredor> corredorReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<corredor>("Model.fk_Corredor_has_Corrida_Corredor", "corredor");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<corredor>("Model.fk_Corredor_has_Corrida_Corredor", "corredor", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for corrida in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "fk_Corredor_has_Corrida_Corrida1", "corrida")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public corrida corrida
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<corrida>("Model.fk_Corredor_has_Corrida_Corrida1", "corrida").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<corrida>("Model.fk_Corredor_has_Corrida_Corrida1", "corrida").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for corrida in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<corrida> corridaReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<corrida>("Model.fk_Corredor_has_Corrida_Corrida1", "corrida");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<corrida>("Model.fk_Corredor_has_Corrida_Corrida1", "corrida", value);
                }
            }
        }
    }
}
